from setuptools import setup, find_packages

setup(
    name="ml_pipeline",
    version="0.1.0",
    description="A Python package",
    author="Generated by Agentic Code Studio",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[],
    extras_require={
        "dev": ["pytest>=7.0", "black", "flake8"],
    },
)
