import pandas as pd
from ml_workflow.data_loader import DataLoader
from ml_workflow.feature_engineering import FeatureEngineering
from ml_workflow.model_trainer import ModelTrainer
from ml_workflow.model_evaluator import ModelEvaluator
from ml_workflow.utils import train_test_split_data

# 1. Load and Preprocess Data
# NOTE: Ensure 'data.csv' exists or use sample_data.csv generated by tests
loader = DataLoader()
try:
    df = loader.load_csv('data.csv')
    X, y = loader.preprocess(df, target_column='target')

    # 2. Split Data
    X_train, X_test, y_train, y_test = train_test_split_data(X, y, test_size=0.2)

    # 3. Feature Engineering (Scaling)
    fe = FeatureEngineering()
    # Scale numeric features only
    X_train_scaled = fe.scale_features(X_train.select_dtypes(include='number'), method='standard')
    X_test_scaled = fe.scale_features(X_test.select_dtypes(include='number'), method='standard')

    # 4. Model Training
    trainer = ModelTrainer()
    model = trainer.train(X_train_scaled, y_train, model_name='RandomForest')

    # 5. Model Evaluation
    evaluator = ModelEvaluator()
    y_pred = model.predict(X_test_scaled)

    metrics = evaluator.calculate_metrics(y_test, y_pred)
    print("Test Metrics:", metrics)

    cv_results = evaluator.cross_validate(model, X_train_scaled, y_train)
    print("Cross Validation Mean Score:", cv_results['mean_score'])

except FileNotFoundError:
    print("Please create a 'data.csv' file or run tests to generate 'sample_data.csv'.")
except Exception as e:
    print(f"An error occurred during workflow execution: {e}")